In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

0

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[-1]

10

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.shape

(11,)

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr[0: 5] = 100

In [11]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
#broadcasting
arr[0: 5] = 25
arr

array([25, 25, 25, 25, 25,  5,  6,  7,  8,  9, 10])

In [15]:
arr = np.arange(0, 11)

In [16]:
slice_of_arr = arr[:5]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [18]:
slice_of_arr[:] = 30

In [19]:
slice_of_arr

array([30, 30, 30, 30, 30])

In [20]:
arr

array([30, 30, 30, 30, 30,  5,  6,  7,  8,  9, 10])

In [22]:
arr = np.arange(0, 11)
arr_copy = np.copy(arr)

In [25]:
arr_copy[:3] = 42
arr_copy

array([42, 42, 42,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [28]:
arr_2d.shape


(3, 3)

In [29]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr_2d[1,2]

6

In [31]:
arr = np.arange(1,11)

In [32]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
bool_arr = arr > 4

In [34]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr[arr > 6]

array([ 7,  8,  9, 10])