In [2]:
import numpy as np

In [3]:
mylist =[1, 2, 3,]

In [4]:
type(mylist)

list

In [5]:
myarr = np.array(mylist)

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [20]:
np.random.rand(5, 2)

array([[0.20085181, 0.44712333],
       [0.72644537, 0.57482816],
       [0.08520574, 0.94939107],
       [0.81648572, 0.96930142],
       [0.2036704 , 0.02222108]])

In [21]:
np.random.randn(2, 3)

array([[ 1.34704977, -1.02165236,  1.25060156],
       [-2.07129193,  1.50676647,  1.93299772]])

In [22]:
np.random.randint(0, 101, (3, 5))

array([[66, 34, 12,  6, 95],
       [81, 51, 11, 70, 41],
       [35, 89, 38,  4, 59]])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [40]:
arr = np.arange(0, 25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.shape

(25,)

In [36]:
arr = arr.reshape(5,5)

In [37]:
arr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int64')

In [28]:
ranarr = np.random.randint(0, 101, 10)

In [29]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [30]:
ranarr.max()

99

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmax()

5

In [33]:
ranarr.argmin()

7

In [34]:
ranarr.dtype

dtype('int64')

In [35]:
type(ranarr)

numpy.ndarray